import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from sqlalchemy.orm import Session
from core.config import settings
from models.db_models import Course, CourseOutcome
from services.ml_predictor import predict_course_risk

logger = logging.getLogger(__name__)

# ── Email Builder ─────────────────────────────

def build_student_email(
    student_name: str,
    course_name: str,
    risk_level: str,
    risk_pct: float,
    at_risk_cos: list,
    early_pct: float,
) -> tuple:
    """Returns (subject, html_body)"""

    co_list_html = "".join(
        f"<li style='margin:6px 0; color:#dc2626;'>"
        f"<strong>{co}</strong></li>"
        for co in at_risk_cos
    ) if at_risk_cos else "<li>No specific COs flagged</li>"

    subject = f"[AcademiQ Alert] Early Warning — {course_name}"

    html = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px;
                margin: 0 auto; padding: 20px;">

      <div style="background: #1e40af; padding: 20px;
                  border-radius: 8px 8px 0 0;">
        <h1 style="color: white; margin: 0; font-size: 22px;">
          AcademiQ Early Alert
        </h1>
        <p style="color: #bfdbfe; margin: 6px 0 0 0; font-size: 13px;">
          Daffodil International University
        </p>
      </div>

      <div style="background: #f8fafc; padding: 24px;
                  border: 1px solid #e2e8f0; border-radius: 0 0 8px 8px;">

        <p style="font-size: 16px; color: #1e293b;">
          Dear <strong>{student_name}</strong>,
        </p>

        <p style="color: #475569; line-height: 1.6;">
          Our AI monitoring system has detected that you may be at risk
          of not achieving the required outcomes in:
        </p>

        <div style="background: #1e40af; color: white; padding: 12px 16px;
                    border-radius: 6px; margin: 16px 0; font-size: 18px;
                    font-weight: bold;">
          {course_name}
        </div>

        <div style="background: {'#fee2e2' if risk_level == 'high' else '#fef3c7'};
                    border-left: 4px solid
                    {'#dc2626' if risk_level == 'high' else '#d97706'};
                    padding: 12px 16px; border-radius: 4px; margin: 16px 0;">
          <strong>Risk Level:</strong>
          {risk_level.upper()} ({risk_pct:.1f}% probability)<br/>
          <strong>Current Performance:</strong> {early_pct:.1f}%
        </div>

        <p style="color: #475569;"><strong>Course Outcomes needing attention:</strong></p>
        <ul style="color: #475569; padding-left: 20px;">
          {co_list_html}
        </ul>

        <div style="background: #f0fdf4; border: 1px solid #bbf7d0;
                    padding: 16px; border-radius: 6px; margin: 20px 0;">
          <p style="color: #166534; margin: 0; font-weight: bold;">
            What you should do:
          </p>
          <ul style="color: #166534; margin: 8px 0 0 0; padding-left: 20px;">
            <li>Contact your course instructor immediately</li>
            <li>Visit the academic support center</li>
            <li>Review materials for the flagged COs</li>
            <li>Form a study group with classmates</li>
          </ul>
        </div>

        <p style="color: #94a3b8; font-size: 12px; margin-top: 24px;
                  border-top: 1px solid #e2e8f0; padding-top: 16px;">
          This alert was generated by AcademiQ AI on
          {datetime.now().strftime('%B %d, %Y at %I:%M %p')}.
          If you believe this is incorrect, please contact your advisor.
        </p>
      </div>
    </div>
    """
    return subject, html


def build_faculty_summary_email(
    faculty_name: str,
    course_name: str,
    high_risk: list,
    medium_risk: list,
) -> tuple:
    """Returns (subject, html_body)"""

    def student_rows(students):
        if not students:
            return "<tr><td colspan='3'>None</td></tr>"
        rows = ""
        for s in students:
            cos = ", ".join(s["at_risk_cos"]) if s["at_risk_cos"] else "—"
            rows += f"""
            <tr>
              <td style="padding:8px; border-bottom:1px solid #e2e8f0;">
                {s['student_name']}</td>
              <td style="padding:8px; border-bottom:1px solid #e2e8f0;">
                {s['risk_pct']:.1f}%</td>
              <td style="padding:8px; border-bottom:1px solid #e2e8f0;
                         color:#dc2626;">{cos}</td>
            </tr>"""
        return rows

    subject = f"[AcademiQ] At-Risk Student Report — {course_name}"

    html = f"""
    <div style="font-family: Arial, sans-serif; max-width: 650px;
                margin: 0 auto; padding: 20px;">

      <div style="background: #1e40af; padding: 20px;
                  border-radius: 8px 8px 0 0;">
        <h1 style="color: white; margin: 0; font-size: 20px;">
          At-Risk Student Report
        </h1>
        <p style="color: #bfdbfe; margin: 4px 0 0 0;">
          {course_name}
        </p>
      </div>

      <div style="padding: 24px; background: #f8fafc;
                  border: 1px solid #e2e8f0; border-radius: 0 0 8px 8px;">
        <p>Dear <strong>{faculty_name}</strong>,</p>
        <p style="color:#475569;">
          AcademiQ has completed its weekly risk analysis.
          Here is your at-risk student summary:
        </p>

        <div style="display:flex; gap:12px; margin:16px 0;">
          <div style="background:#fee2e2; padding:12px 20px;
                      border-radius:8px; text-align:center;">
            <div style="font-size:28px; font-weight:bold;
                        color:#dc2626;">{len(high_risk)}</div>
            <div style="color:#dc2626; font-size:12px;">High Risk</div>
          </div>
          <div style="background:#fef3c7; padding:12px 20px;
                      border-radius:8px; text-align:center;">
            <div style="font-size:28px; font-weight:bold;
                        color:#d97706;">{len(medium_risk)}</div>
            <div style="color:#d97706; font-size:12px;">Medium Risk</div>
          </div>
        </div>

        <h3 style="color:#dc2626;">High Risk Students</h3>
        <table style="width:100%; border-collapse:collapse;
                      font-size:13px;">
          <tr style="background:#fee2e2;">
            <th style="padding:8px; text-align:left;">Student</th>
            <th style="padding:8px; text-align:left;">Risk %</th>
            <th style="padding:8px; text-align:left;">At-risk COs</th>
          </tr>
          {student_rows(high_risk)}
        </table>

        <h3 style="color:#d97706; margin-top:20px;">Medium Risk Students</h3>
        <table style="width:100%; border-collapse:collapse;
                      font-size:13px;">
          <tr style="background:#fef3c7;">
            <th style="padding:8px; text-align:left;">Student</th>
            <th style="padding:8px; text-align:left;">Risk %</th>
            <th style="padding:8px; text-align:left;">At-risk COs</th>
          </tr>
          {student_rows(medium_risk)}
        </table>

        <p style="color:#94a3b8; font-size:12px; margin-top:24px;
                  border-top:1px solid #e2e8f0; padding-top:16px;">
          Generated by AcademiQ on
          {datetime.now().strftime('%B %d, %Y at %I:%M %p')}
        </p>
      </div>
    </div>
    """
    return subject, html


# ── Email Sender ──────────────────────────────

def send_email(to_email: str, subject: str, html_body: str) -> dict:
    """
    Send an HTML email via SMTP.
    Returns dict with success status and message.
    """
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = settings.SMTP_FROM
        msg["To"]      = to_email
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
            server.sendmail(settings.SMTP_FROM, to_email, msg.as_string())

        logger.info(f"Email sent to {to_email}")
        return {"success": True, "message": f"Email sent to {to_email}"}

    except Exception as e:
        logger.error(f"Email failed to {to_email}: {str(e)}")
        return {"success": False, "message": str(e)}


# ── Main Alert Trigger ────────────────────────

def trigger_course_alerts(
    course_id: int,
    db: Session,
    dry_run: bool = True
) -> dict:
    """
    Run risk prediction and send alerts to at-risk students.

    dry_run=True  → simulate alerts without sending real emails
    dry_run=False → send real emails (requires SMTP config in .env)
    """
    from models.db_models import User
    from database.crud import get_user_by_id

    course = db.query(Course).filter(Course.id == course_id).first()
    if not course:
        return {"error": "Course not found"}

    # Get faculty info
    faculty = get_user_by_id(db, course.faculty_id)

    # Run ML predictions
    predictions = predict_course_risk(course_id, db)
    if not predictions or "error" in predictions[0]:
        return {"error": "Could not run predictions. Is the model trained?"}

    high_risk   = [p for p in predictions if p["risk_level"] == "high"]
    medium_risk = [p for p in predictions if p["risk_level"] == "medium"]
    alerts_sent = []
    alerts_log  = []

    # ── Alert each at-risk student ────────────
    for student_data in high_risk + medium_risk:
        student = db.query(User).filter(
            User.id == student_data["student_id"]
        ).first()
        if not student:
            continue

        subject, html = build_student_email(
            student_name = student.name,
            course_name  = course.name,
            risk_level   = student_data["risk_level"],
            risk_pct     = student_data["risk_pct"],
            at_risk_cos  = student_data["at_risk_cos"],
            early_pct    = student_data["early_pct"],
        )

        alert_entry = {
            "student_id":   student.id,
            "student_name": student.name,
            "email":        student.email,
            "risk_level":   student_data["risk_level"],
            "risk_pct":     student_data["risk_pct"],
            "at_risk_cos":  student_data["at_risk_cos"],
            "subject":      subject,
        }

        if not dry_run:
            result = send_email(student.email, subject, html)
            alert_entry["email_sent"]    = result["success"]
            alert_entry["email_message"] = result["message"]
        else:
            alert_entry["email_sent"]    = None
            alert_entry["email_message"] = "DRY RUN — no email sent"

        alerts_log.append(alert_entry)

    # ── Alert faculty with summary ────────────
    if faculty:
        subject, html = build_faculty_summary_email(
            faculty_name = faculty.name,
            course_name  = course.name,
            high_risk    = high_risk,
            medium_risk  = medium_risk,
        )
        if not dry_run:
            send_email(faculty.email, subject, html)

    return {
        "course_id":       course_id,
        "course_name":     course.name,
        "dry_run":         dry_run,
        "total_predicted": len(predictions),
        "high_risk_count": len(high_risk),
        "med_risk_count":  len(medium_risk),
        "alerts_log":      alerts_log,
        "triggered_at":    datetime.now().isoformat(),
    }